import type { Metadata } from "next";
import { Inter, Fira_Code } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import AdminPanelLayout from "@/components/admin-panel/admin-panel-layout";

const inter = Inter({ 
  subsets: ["latin"], 
  variable: "--font-sans" 
});

const firaCode = Fira_Code({ 
  subsets: ["latin"], 
  variable: "--font-mono" 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // Injecting the variables here makes them available globally.
      // We also add "font-sans" so Inter is the default everywhere.
      className={cn("h-full antialiased font-sans", inter.variable, firaCode.variable)}
    >
      <body className="min-h-full flex flex-col">
        <AdminPanelLayout>
          {children}
        </AdminPanelLayout>
      </body>
    </html>
  );
}